app/models.py
from typing import Optional
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import String, Boolean
from sqlalchemy.orm import Mapped, mapped_column

db = SQLAlchemy()


class Quest(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(80), index=True)
    zags: Mapped[bool] = mapped_column(Boolean())
    drink: Mapped[Optional[str]] = mapped_column(String(80))
    food: Mapped[str] = mapped_column(String(5))

app/__init__.py
from flask import Flask
import logging, os
from logging.handlers import RotatingFileHandler, SMTPHandler


def create_app():  # application factory
    app = Flask(__name__)
    config_type = os.environ.get('CONFIG_TYPE') or 'config.Config'  # needed to switch to test config
    app.config.from_object(config_type)

    from app import routes
    app.register_blueprint(routes.bp)  # needed to find the routes

    from app.models import db
    db.init_app(app)

    with app.app_context():  # create DB tables if not exist
        db.create_all()

    initialize_loggers(app, config_type)

    return app


def initialize_loggers(app, config_type):
    if not os.path.exists('logs'):  # create directory for logs if not exists
        os.mkdir('logs')
    if config_type == 'config.Config':
        file_handler = RotatingFileHandler('logs/website.log', maxBytes=102400,
                                           backupCount=10)  # keep 10 last log files size of 100kb
    else:
        file_handler = RotatingFileHandler('logs/website_test.log', maxBytes=102400)  # keep only 1 file
    log_format = logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')  # custom formatting for the log messages
    file_handler.setFormatter(log_format)
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)
    app.logger.setLevel(logging.INFO)
    app.logger.info('Website startup')  # writes to the logs each time server starts

    if config_type == 'config.Config':  # mail alerts to be sent only for prod config
        mail_handler = SMTPHandler(
            mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
            fromaddr=app.config['MAIL_FROM'],
            toaddrs=app.config['ADMINS'],
            subject='Wedding website Error',
            credentials=(app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD']),
            secure=()
        )
        mail_handler.setFormatter(log_format)
        mail_handler.setLevel(logging.ERROR)  # send email when error occur
        app.logger.addHandler(mail_handler)

app/routes.py
from flask import render_template, redirect, request, Blueprint, current_app
from flask_wtf import FlaskForm
from app.models import Quest, db

bp = Blueprint("routes", __name__)


@bp.route('/')
def index():
    form = FlaskForm()  # needed to use form.hidden_tag() field
    return render_template('index.html', form=form)


@bp.route('/submit', methods=['POST'])
def submit():
    quest = Quest(
        name=request.form['name'],
        zags=bool(int(request.form['zags'])),  # convert form value from str to int (0, 1) and next to bool
        drink=request.form['drink'],
        food=request.form['food']
    )

    db.session.add(quest)
    db.session.commit()

    current_app.logger.info("Questionary successfully submitted")  # writes to the logs each time form is submitted

    return redirect('/#popup')  # needed to shown the "thanks" message


@bp.route('/quests')
def quests():
    page = request.args.get('page', 1, type=int)  # pagination
    pagination = db.paginate(db.Select(Quest), page=page, per_page=15)

    quest_all = db.session.execute(db.Select(Quest)).scalars().all()
    total = {"zags": 0, "meat": 0, "fish": 0, "bird": 0}  # calculate total values from DB for statistics
    for quest in quest_all:
        if quest.zags:
            total["zags"] += 1
        total[quest.food] += 1

    return render_template('quests.html', total=total, pagination=pagination)

app/templates/index.html
<!DOCTYPE html> <!-- https://validator.w3.org/ can be used to check for issues -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:700&display=swap">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://polyfill.io/v3/polyfill.min.js"></script> <!-- automatically identify and provide all of the polyfills, to run the same on older browsers -->
    <title>Evgenia & Roman wedding</title>
  </head>
  <body>

    <nav id="navbar">
      <ul>
        <li><a href="#memo">Памятка</a></li>
        <li><a href="#survey">Опрос</a></li>
        <li><a href="#gallery">Галерея</a></li>
      </ul>
    </nav>

    <section id="memo">
      <h1>Памятка</h1>
      <div class="memo-form">
        <p>Роспись (по желанию): 1 июня 20:20, Дворец бракосочетания №2 (<a href="#zags-map">Фурштатская 52</a>)</p>
        <p>Фуршет: 2 июня 16:00, двор "Сезоны в Парке" (<a href="#rest-outside">Писарева 3А</a>)</p>
        <p>Ресторан: 2 июня 17:00, Ресторан "Сезоны в Парке" (<a href="#rest-map">Писарева 3А</a>)</p>
        <p>Мы будем благодарны, если Вы поддержите <a href="#palette">цветовое решение</a> свадьбы</p>
        <p>P.S. пожалуйста, не дарите нам цветы, мы уедем и не успеем ими полюбоваться</p>
      </div>
    </section>

    <section id="survey">
      <h1>Опрос</h1>
      <div class="survey-form">
        <form action="/submit" method="POST">
            {{ form.hidden_tag() }} <!-- generates a hidden field that includes a token that is used to protect the form against CSRF attacks -->
            <div>
                <label for="name">Ваше имя: </label>
                <input type="text" id="name" name="name" required maxlength="80" spellcheck="false">
            </div>
            <div>
                <label for="zags">Идете на регистрацию? </label>
                <input type="checkbox" id="zags" name="zags" value="1">
                <input type="hidden" name="zags" value="0"> <!-- hidden input with same name as checkbox helps to resolve bad request if checkbox not selected ("neither the name nor the value is submitted to the server", so it takes value of this hidden input as it has same name) -->
            </div>
            <div>
                <label for="drink">Что пьете?</label>                
                <input type="text" id="drink" name="drink" maxlength="80">
            </div>
            <div class="dish">
                <p class="tooltip">
                    <input type="radio" id="fish" name="food" value="fish" checked>
                    <label for="fish">Рыба </label>
                    <span class="tooltiptext">Треска, отварной картофель стоун и соус айоли</span>
                </p>
                <p class="tooltip">
                    <input type="radio" id="meat" name="food" value="meat">
                    <label for="meat">Мясо </label>
                    <span class="tooltiptext">Щёчки, полба и пастернак</span> <!-- popup for food options -->
                </p>
                <p class="tooltip">
                    <input type="radio" id="bird" name="food" value="bird">
                    <label for="bird">Птица </label>
                    <span class="tooltiptext">Жареный цыпленок с ореховым соусом</span>
                </p>
            </div>
            <input type="submit" value="Отправить">
        </form>
      </div>
      
      <div class="popup-overlay" id="popup"> <!-- popup after form submitted -->
        <div class="popup-msg">
            <a class="popup-close" href="#survey">&times;</a>
            <p>Благодарим за предоставленную информацию</p>
        </div>
      </div>

    </section>

    <section id="gallery">
      <h1>Галерея</h1>
      <div class="photos-grid">
        <a
          class="photo-tile"
          href="http://kzags.gov.spb.ru/palaces/24"
          target="_blank"
        >
          <img src="{{ url_for('static', filename='zags.jpg') }}" alt="Дворец бракосочетания">
          <p>Дворец бракосочетания №2</p>
        </a>
        <a
          class="photo-tile"
          id="rest-outside"
          href="https://yandex.ru/maps/-/CDq3u4KH"
          target="_blank"
        >
          <img src="{{ url_for('static', filename='outside.jpg') }}" alt="Двор ресторана Сезоны в Парке">
          <p>Двор "Сезоны в Парке"</p>
        </a>
        <a
          class="photo-tile"
          href="https://barsezony.ru/vparke"
          target="_blank"
        >
          <img src="{{ url_for('static', filename='inside.jpeg') }}" alt="Ресторан Сезоны в Парке">
          <p>Ресторан "Сезоны в Парке"</p>
        </a>

        <iframe
            id="zags-map"
            src="https://yandex.ru/map-widget/v1/?um=constructor%3A5c15ef690e7728867793347a6ff75034dfb0c9af05bf137430db23c0a17cf4cc&amp;source=constructor"
            width="100%"
            height="100%"
            frameborder="0"
        ></iframe>
        <a
            id="palette"
            class="photo-tile"
        >
          <img src="{{ url_for('static', filename='palette.png') }}" alt="Цветовая гамма">
          <p>Цветовая гамма</p>
        </a>
        <iframe
            id="rest-map"
            src="https://yandex.ru/map-widget/v1/?um=constructor%3A2434132ae32b5528063fd9c8c110c8e0f74c413913a6e77f29c8525491e80cf4&amp;source=constructor"
            width="100%"
            height="100%"
            frameborder="0"
        ></iframe>
      </div>
    </section>
  </body>
</html>

app/templates/quests.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>Questionary results</title>
</head>
<body>
    <table>
        <tr>
            <th>id</th>
            <th>Имя</th>
            <th>Загс</th>
            <th>Напиток</th>
            <th>Еда</th>
        </tr>
        {% for quest in pagination %}
        <tr>
            <td>{{ quest.id }}</td>
            <td>{{ quest.name }}</td>
            <td>{{ quest.zags }}</td>
            <td>{{ quest.drink }}</td>
            <td>{{ quest.food }}</td>
        </tr>
        {% endfor %}
        <tr>
            <th colspan="2">Итого</th>
            <th>{{ total["zags"] }}</th>
            <th colspan="2">Meat: {{ total["meat"] }} / Fish: {{ total["fish"] }} / Bird: {{ total["bird"] }}</th>
        </tr>
    </table>

    <div class="page-items"> <!-- Pagination widget below content -->
        {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }} answers
    </div>
    <div class="pagination">Pages: 
        {% for page in pagination.iter_pages() %}
            {% if page != pagination.page %}
                <a href="{{ url_for('routes.quests', page=page) }}"> {{ page }} </a>
            {% else %}
                <strong> {{ page }} </strong>
            {% endif %}
        {% endfor %}
    </div>

</body>
</html>